# Number guessing game built in python
'''
features: Generate a random number between 1 and 100.
          Allow the user to input guesses and provide feedback on whether the guess is too high, too low, or correct.
          Track the number of attempts and display it when the user guesses correctly.
'''

import random

def play_game():
    lowest_num = 1
    highest_num = 100
    random_number = random.randint(lowest_num, highest_num)

    guesses = 0
    is_correct = True

    print("\nWELCOME TO RANDOM NUMBER GUESSING GAME")
    print(f"Guess the random number generated by the computer between {lowest_num} and {highest_num}:\n")

    while is_correct:

        user_input = input("Enter the number guessed:")

        if user_input.isdigit():

            number = int(user_input)
            guesses += 1

            if number < lowest_num or number > highest_num:
                print(f"Number out of range, please enter the number between {lowest_num} & {highest_num}.")

            elif number < random_number:
                print("Very low, Please try hihger numeber.")

            elif number > random_number:
                print("Very high, please try lower numebr")
            
            else:
                print(f"your guessed number is correct {number}")
                print(f"You have guessed the number in {guesses} attempts.")
                is_correct = False

        else:
            print("Invalid input! Please give the numeric input.")

def main():
    play = True
    while play:
        play_game()
        play_again = input("\nyou want to play again (type 'yes'):").lower()
        
        if play_again == "yes":
            play = True

        else:
            play = False
            print("End of game")
            break 

main()

